### ISSUE TITLE
Mac版におけるUIのバグ

### ISSUE THREAD

**Issue by hamadatakaki** [approvers/devoirs#36]
## 環境
MacOS Mojave 10.14.6

## 概要

以下のSCのように「＾」が透けて見える.

![image](https://user-images.githubusercontent.com/22311903/87844186-e0116300-c8f5-11ea-9930-388c81a335e1.png)

**Comment by Siketyan** [comment]
Windows でも確認しました．
修正します

**Comment by Siketyan** [comment]
https://github.com/approvers/devoirs/releases/tag/v1.0.1
